[build]
  base    = "site"
  command = "gem install bundler && bundle install && bundle exec jekyll build"
  publish = "site/_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.0"
