title: "DevPulse Blog"
description: ."Daily coding tutorials, guides and project ideas for developers."
url: "https://devpulseblog.netlify.app"
baseurl: ""
author: DevPulse Team"
lang: "en-US"
theme: minima
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 9
paginate_path: "/page:num/"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - netlify.toml
  - scripts/
  - requirements.txt
  - README.md
  - article_log.json
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
